### ISSUE TITLE
Loss is nan when training my own dataset

### ISSUE THREAD

**Issue by InfinityBox** [raoyongming/DynamicViT#6]
It would happen randomly in any epoch. And it still appears after setting a lower learning rate or turning off the amp. 

Then I found it usually occurs in module 'PredictorLG', if 'policy' is an all-zero matrix, there will be nan in global_x.

Is it ok to add a very small value in the denominator of the global_x, e.g. 1e-6?

**Comment by raoyongming** [comment]
I think it is ok to add a small value in this [line](https://github.com/raoyongming/DynamicViT/blob/206a43ecc17eca6ad96dadd509404b19de9783ab/vit.py#L311). Since the following layers are fully learnable, I think it may also ok to add any positive constant to the denominator of `global_x` (e.g., 1) to avoid `nan` values.

**Comment by InfinityBox** [comment]
Thank you so much for your quick response!
